{% set name = "PyTrack" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cosbidev/PyTrack/archive/v{{ version }}.tar.gz
  sha256: d4ee9bda66523f79c9118f15ed1eca5e7a714d36713c0dd6710083f2c7b34235

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - folium >=0.12.1.post1,==0.12.1.*
    - python-graphviz >=3.0.0,==3.0.*
    - matplotlib-base >=3.5.2,==3.5.*
    - networkx >=2.8.2,==2.8.*
    - numpy >=1.22.3,==1.22.*
    - pandas >=1.4.2,==1.4.*
    - pydot >=1.2.4,==1.2.*
    - pyproj >=3.3.1,==3.3.*
    - python
    - requests >=2.27.1,==2.27.*
    - scikit-learn >=1.1.1,==1.1.*
    - setuptools >=62.3.2,==62.3.*
    - shapely >=1.8.2,==1.8.*

test:
  imports:
    - pytrack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cosbidev/PyTrack
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mtortora-ai
